#!/usr/bin/env python3
"""
Generates OpenXR dispatch table header and source from xr.xml.
Based on the pattern used in OpenXR-SDK-Source but simplified for MonoEye.
"""

import argparse
import xml.etree.ElementTree as ET
import re

def parse_commands(xml_path):
    """Parse xr.xml to extract all OpenXR commands."""
    tree = ET.parse(xml_path)
    root = tree.getroot()

    commands = {}

    for cmd_elem in root.findall('.//commands/command'):
        # Skip aliases
        if cmd_elem.get('alias'):
            continue

        proto = cmd_elem.find('proto')
        if proto is None:
            continue

        ret_type_elem = proto.find('type')
        name_elem = proto.find('name')
        if ret_type_elem is None or name_elem is None:
            continue

        ret_type = ret_type_elem.text or 'void'
        # Get full type text including any pointer asterisks
        ret_text = proto.text or ''
        if ret_type_elem.tail:
            ret_text += ret_type_elem.tail
        ret_type = ret_text.strip()
        if not ret_type:
            ret_type = 'void'

        cmd_name = name_elem.text or ''
        if not cmd_name:
            continue

        # Parse parameters
        params = []
        for param_elem in proto.findall('param'):
            type_elem = param_elem.find('type')
            name_param_elem = param_elem.find('name')
            if type_elem is None or name_param_elem is None:
                continue

            # Get full type including pointers
            param_type = (param_elem.text or '') + (type_elem.text or '') + (type_elem.tail or '')
            param_type = param_type.strip()
            param_name = name_param_elem.text or ''

            params.append((param_type, param_name))

        commands[cmd_name] = {
            'return_type': ret_type,
            'params': params,
        }

    return commands


def generate_dispatch_header(commands, output_path):
    """Generate the dispatch table header file."""
    with open(output_path, 'w') as f:
        f.write("""// Copyright (c) 2026 MonoEye Contributors
// SPDX-License-Identifier: Apache-2.0
//
// AUTO-GENERATED - DO NOT EDIT
// Generated by scripts/generate_dispatch.py

#pragma once

#include <openxr/openxr.h>

namespace monoeye {

struct XrGeneratedDispatchTable {
""")

        for cmd_name, cmd_info in sorted(commands.items()):
            # Build function pointer type name
            fp_type = f"PFN_{cmd_name}"
            member_name = cmd_name[2:]  # Remove xr prefix

            f.write(f"    {fp_type} {member_name} = nullptr;\n")

        f.write("""};

} // namespace monoeye
""")

    print(f"Generated dispatch header: {output_path}")


def generate_dispatch_source(commands, output_path):
    """Generate the dispatch table source file."""
    with open(output_path, 'w') as f:
        f.write("""// Copyright (c) 2026 MonoEye Contributors
// SPDX-License-Identifier: Apache-2.0
//
// AUTO-GENERATED - DO NOT EDIT
// Generated by scripts/generate_dispatch.py

#include "dispatch_table.h"
#include "xr_generated_dispatch_table.h"
#include <cstring>

namespace monoeye {

void GeneratedXrPopulateDispatchTable(
    XrGeneratedDispatchTable* dispatch_table,
    XrInstance instance,
    PFN_xrGetInstanceProcAddr get_instance_proc_addr
) {
    if (!dispatch_table || !get_instance_proc_addr) {
        return;
    }

    PFN_xrVoidFunction proc_addr = nullptr;
""")

        for cmd_name, cmd_info in sorted(commands.items()):
            member_name = cmd_name[2:]
            f.write(f'\n    get_instance_proc_addr(instance, "{cmd_name}", &proc_addr);\n')
            f.write(f"    dispatch_table->{member_name} = reinterpret_cast<{cmd_name}>(proc_addr);\n")

        f.write("""
}

void MonoEyeCleanUpDispatchTable(XrGeneratedDispatchTable* dispatch_table) {
    if (dispatch_table) {
        delete dispatch_table;
    }
}

} // namespace monoeye
""")

    print(f"Generated dispatch source: {output_path}")


def main():
    parser = argparse.ArgumentParser(description='Generate OpenXR dispatch table')
    parser.add_argument('--xr-xml', required=True, help='Path to xr.xml')
    parser.add_argument('--output-dir', required=True, help='Output directory')
    args = parser.parse_args()

    commands = parse_commands(args.xr_xml)

    print(f"Parsed {len(commands)} commands from xr.xml")

    header_path = f"{args.output_dir}/xr_generated_dispatch_table.h"
    source_path = f"{args.output_dir}/xr_generated_dispatch_table.cpp"

    generate_dispatch_header(commands, header_path)
    generate_dispatch_source(commands, source_path)


if __name__ == '__main__':
    main()
