// Copyright (c) 2026 MonoEye Contributors
// SPDX-License-Identifier: Apache-2.0
//
// AUTO-GENERATED - DO NOT EDIT
// Generated by scripts/generate_dispatch.py

#include "dispatch_table.h"
#include "xr_generated_dispatch_table.h"
#include <cstring>

namespace monoeye {

void GeneratedXrPopulateDispatchTable(
    XrGeneratedDispatchTable* dispatch_table,
    XrInstance instance,
    PFN_xrGetInstanceProcAddr get_instance_proc_addr
) {
    if (!dispatch_table || !get_instance_proc_addr) {
        return;
    }

    PFN_xrVoidFunction proc_addr = nullptr;

    get_instance_proc_addr(instance, "xrAcquireEnvironmentDepthImageMETA", &proc_addr);
    dispatch_table->AcquireEnvironmentDepthImageMETA = proc_addr;

    get_instance_proc_addr(instance, "xrAcquireSwapchainImage", &proc_addr);
    dispatch_table->AcquireSwapchainImage = proc_addr;

    get_instance_proc_addr(instance, "xrAddTrackableImageDatabaseANDROID", &proc_addr);
    dispatch_table->AddTrackableImageDatabaseANDROID = proc_addr;

    get_instance_proc_addr(instance, "xrAllocateWorldMeshBufferML", &proc_addr);
    dispatch_table->AllocateWorldMeshBufferML = proc_addr;

    get_instance_proc_addr(instance, "xrApplyForceFeedbackCurlMNDX", &proc_addr);
    dispatch_table->ApplyForceFeedbackCurlMNDX = proc_addr;

    get_instance_proc_addr(instance, "xrApplyFoveationHTC", &proc_addr);
    dispatch_table->ApplyFoveationHTC = proc_addr;

    get_instance_proc_addr(instance, "xrApplyHapticFeedback", &proc_addr);
    dispatch_table->ApplyHapticFeedback = proc_addr;

    get_instance_proc_addr(instance, "xrAttachSessionActionSets", &proc_addr);
    dispatch_table->AttachSessionActionSets = proc_addr;

    get_instance_proc_addr(instance, "xrBeginFrame", &proc_addr);
    dispatch_table->BeginFrame = proc_addr;

    get_instance_proc_addr(instance, "xrBeginPlaneDetectionEXT", &proc_addr);
    dispatch_table->BeginPlaneDetectionEXT = proc_addr;

    get_instance_proc_addr(instance, "xrBeginSession", &proc_addr);
    dispatch_table->BeginSession = proc_addr;

    get_instance_proc_addr(instance, "xrCancelFutureEXT", &proc_addr);
    dispatch_table->CancelFutureEXT = proc_addr;

    get_instance_proc_addr(instance, "xrCaptureSceneAsyncBD", &proc_addr);
    dispatch_table->CaptureSceneAsyncBD = proc_addr;

    get_instance_proc_addr(instance, "xrCaptureSceneCompleteBD", &proc_addr);
    dispatch_table->CaptureSceneCompleteBD = proc_addr;

    get_instance_proc_addr(instance, "xrChangeVirtualKeyboardTextContextMETA", &proc_addr);
    dispatch_table->ChangeVirtualKeyboardTextContextMETA = proc_addr;

    get_instance_proc_addr(instance, "xrClearSpatialAnchorStoreMSFT", &proc_addr);
    dispatch_table->ClearSpatialAnchorStoreMSFT = proc_addr;

    get_instance_proc_addr(instance, "xrComputeNewSceneMSFT", &proc_addr);
    dispatch_table->ComputeNewSceneMSFT = proc_addr;

    get_instance_proc_addr(instance, "xrConvertTimeToTimespecTimeKHR", &proc_addr);
    dispatch_table->ConvertTimeToTimespecTimeKHR = proc_addr;

    get_instance_proc_addr(instance, "xrConvertTimeToWin32PerformanceCounterKHR", &proc_addr);
    dispatch_table->ConvertTimeToWin32PerformanceCounterKHR = proc_addr;

    get_instance_proc_addr(instance, "xrConvertTimespecTimeToTimeKHR", &proc_addr);
    dispatch_table->ConvertTimespecTimeToTimeKHR = proc_addr;

    get_instance_proc_addr(instance, "xrConvertWin32PerformanceCounterToTimeKHR", &proc_addr);
    dispatch_table->ConvertWin32PerformanceCounterToTimeKHR = proc_addr;

    get_instance_proc_addr(instance, "xrCreateAction", &proc_addr);
    dispatch_table->CreateAction = proc_addr;

    get_instance_proc_addr(instance, "xrCreateActionSet", &proc_addr);
    dispatch_table->CreateActionSet = proc_addr;

    get_instance_proc_addr(instance, "xrCreateActionSpace", &proc_addr);
    dispatch_table->CreateActionSpace = proc_addr;

    get_instance_proc_addr(instance, "xrCreateAnchorSpaceANDROID", &proc_addr);
    dispatch_table->CreateAnchorSpaceANDROID = proc_addr;

    get_instance_proc_addr(instance, "xrCreateAnchorSpaceBD", &proc_addr);
    dispatch_table->CreateAnchorSpaceBD = proc_addr;

    get_instance_proc_addr(instance, "xrCreateApiLayerInstance", &proc_addr);
    dispatch_table->CreateApiLayerInstance = proc_addr;

    get_instance_proc_addr(instance, "xrCreateBodyTrackerBD", &proc_addr);
    dispatch_table->CreateBodyTrackerBD = proc_addr;

    get_instance_proc_addr(instance, "xrCreateBodyTrackerFB", &proc_addr);
    dispatch_table->CreateBodyTrackerFB = proc_addr;

    get_instance_proc_addr(instance, "xrCreateBodyTrackerHTC", &proc_addr);
    dispatch_table->CreateBodyTrackerHTC = proc_addr;

    get_instance_proc_addr(instance, "xrCreateDebugUtilsMessengerEXT", &proc_addr);
    dispatch_table->CreateDebugUtilsMessengerEXT = proc_addr;

    get_instance_proc_addr(instance, "xrCreateDeviceAnchorPersistenceANDROID", &proc_addr);
    dispatch_table->CreateDeviceAnchorPersistenceANDROID = proc_addr;

    get_instance_proc_addr(instance, "xrCreateEnvironmentDepthProviderMETA", &proc_addr);
    dispatch_table->CreateEnvironmentDepthProviderMETA = proc_addr;

    get_instance_proc_addr(instance, "xrCreateEnvironmentDepthSwapchainMETA", &proc_addr);
    dispatch_table->CreateEnvironmentDepthSwapchainMETA = proc_addr;

    get_instance_proc_addr(instance, "xrCreateEnvironmentRaycasterAsyncMETA", &proc_addr);
    dispatch_table->CreateEnvironmentRaycasterAsyncMETA = proc_addr;

    get_instance_proc_addr(instance, "xrCreateEnvironmentRaycasterCompleteMETA", &proc_addr);
    dispatch_table->CreateEnvironmentRaycasterCompleteMETA = proc_addr;

    get_instance_proc_addr(instance, "xrCreateExportedLocalizationMapML", &proc_addr);
    dispatch_table->CreateExportedLocalizationMapML = proc_addr;

    get_instance_proc_addr(instance, "xrCreateEyeTrackerANDROID", &proc_addr);
    dispatch_table->CreateEyeTrackerANDROID = proc_addr;

    get_instance_proc_addr(instance, "xrCreateEyeTrackerFB", &proc_addr);
    dispatch_table->CreateEyeTrackerFB = proc_addr;

    get_instance_proc_addr(instance, "xrCreateFaceTracker2FB", &proc_addr);
    dispatch_table->CreateFaceTracker2FB = proc_addr;

    get_instance_proc_addr(instance, "xrCreateFaceTrackerANDROID", &proc_addr);
    dispatch_table->CreateFaceTrackerANDROID = proc_addr;

    get_instance_proc_addr(instance, "xrCreateFaceTrackerBD", &proc_addr);
    dispatch_table->CreateFaceTrackerBD = proc_addr;

    get_instance_proc_addr(instance, "xrCreateFaceTrackerFB", &proc_addr);
    dispatch_table->CreateFaceTrackerFB = proc_addr;

    get_instance_proc_addr(instance, "xrCreateFacialExpressionClientML", &proc_addr);
    dispatch_table->CreateFacialExpressionClientML = proc_addr;

    get_instance_proc_addr(instance, "xrCreateFacialTrackerHTC", &proc_addr);
    dispatch_table->CreateFacialTrackerHTC = proc_addr;

    get_instance_proc_addr(instance, "xrCreateFoveationProfileFB", &proc_addr);
    dispatch_table->CreateFoveationProfileFB = proc_addr;

    get_instance_proc_addr(instance, "xrCreateGeometryInstanceFB", &proc_addr);
    dispatch_table->CreateGeometryInstanceFB = proc_addr;

    get_instance_proc_addr(instance, "xrCreateHandMeshSpaceMSFT", &proc_addr);
    dispatch_table->CreateHandMeshSpaceMSFT = proc_addr;

    get_instance_proc_addr(instance, "xrCreateHandTrackerEXT", &proc_addr);
    dispatch_table->CreateHandTrackerEXT = proc_addr;

    get_instance_proc_addr(instance, "xrCreateInstance", &proc_addr);
    dispatch_table->CreateInstance = proc_addr;

    get_instance_proc_addr(instance, "xrCreateKeyboardSpaceFB", &proc_addr);
    dispatch_table->CreateKeyboardSpaceFB = proc_addr;

    get_instance_proc_addr(instance, "xrCreateLightEstimatorANDROID", &proc_addr);
    dispatch_table->CreateLightEstimatorANDROID = proc_addr;

    get_instance_proc_addr(instance, "xrCreateMarkerDetectorML", &proc_addr);
    dispatch_table->CreateMarkerDetectorML = proc_addr;

    get_instance_proc_addr(instance, "xrCreateMarkerSpaceML", &proc_addr);
    dispatch_table->CreateMarkerSpaceML = proc_addr;

    get_instance_proc_addr(instance, "xrCreateMarkerSpaceVARJO", &proc_addr);
    dispatch_table->CreateMarkerSpaceVARJO = proc_addr;

    get_instance_proc_addr(instance, "xrCreatePassthroughColorLutMETA", &proc_addr);
    dispatch_table->CreatePassthroughColorLutMETA = proc_addr;

    get_instance_proc_addr(instance, "xrCreatePassthroughFB", &proc_addr);
    dispatch_table->CreatePassthroughFB = proc_addr;

    get_instance_proc_addr(instance, "xrCreatePassthroughHTC", &proc_addr);
    dispatch_table->CreatePassthroughHTC = proc_addr;

    get_instance_proc_addr(instance, "xrCreatePassthroughLayerANDROID", &proc_addr);
    dispatch_table->CreatePassthroughLayerANDROID = proc_addr;

    get_instance_proc_addr(instance, "xrCreatePassthroughLayerFB", &proc_addr);
    dispatch_table->CreatePassthroughLayerFB = proc_addr;

    get_instance_proc_addr(instance, "xrCreatePersistedAnchorSpaceANDROID", &proc_addr);
    dispatch_table->CreatePersistedAnchorSpaceANDROID = proc_addr;

    get_instance_proc_addr(instance, "xrCreatePlaneDetectorEXT", &proc_addr);
    dispatch_table->CreatePlaneDetectorEXT = proc_addr;

    get_instance_proc_addr(instance, "xrCreateReferenceSpace", &proc_addr);
    dispatch_table->CreateReferenceSpace = proc_addr;

    get_instance_proc_addr(instance, "xrCreateRenderModelAssetEXT", &proc_addr);
    dispatch_table->CreateRenderModelAssetEXT = proc_addr;

    get_instance_proc_addr(instance, "xrCreateRenderModelEXT", &proc_addr);
    dispatch_table->CreateRenderModelEXT = proc_addr;

    get_instance_proc_addr(instance, "xrCreateRenderModelSpaceEXT", &proc_addr);
    dispatch_table->CreateRenderModelSpaceEXT = proc_addr;

    get_instance_proc_addr(instance, "xrCreateSceneMSFT", &proc_addr);
    dispatch_table->CreateSceneMSFT = proc_addr;

    get_instance_proc_addr(instance, "xrCreateSceneMeshSnapshotANDROID", &proc_addr);
    dispatch_table->CreateSceneMeshSnapshotANDROID = proc_addr;

    get_instance_proc_addr(instance, "xrCreateSceneMeshingTrackerANDROID", &proc_addr);
    dispatch_table->CreateSceneMeshingTrackerANDROID = proc_addr;

    get_instance_proc_addr(instance, "xrCreateSceneObserverMSFT", &proc_addr);
    dispatch_table->CreateSceneObserverMSFT = proc_addr;

    get_instance_proc_addr(instance, "xrCreateSenseDataProviderBD", &proc_addr);
    dispatch_table->CreateSenseDataProviderBD = proc_addr;

    get_instance_proc_addr(instance, "xrCreateSession", &proc_addr);
    dispatch_table->CreateSession = proc_addr;

    get_instance_proc_addr(instance, "xrCreateSoundFieldBD", &proc_addr);
    dispatch_table->CreateSoundFieldBD = proc_addr;

    get_instance_proc_addr(instance, "xrCreateSoundObjectBD", &proc_addr);
    dispatch_table->CreateSoundObjectBD = proc_addr;

    get_instance_proc_addr(instance, "xrCreateSoundObstacleBD", &proc_addr);
    dispatch_table->CreateSoundObstacleBD = proc_addr;

    get_instance_proc_addr(instance, "xrCreateSoundObstacleMaterialBD", &proc_addr);
    dispatch_table->CreateSoundObstacleMaterialBD = proc_addr;

    get_instance_proc_addr(instance, "xrCreateSpaceFromCoordinateFrameUIDML", &proc_addr);
    dispatch_table->CreateSpaceFromCoordinateFrameUIDML = proc_addr;

    get_instance_proc_addr(instance, "xrCreateSpaceUserFB", &proc_addr);
    dispatch_table->CreateSpaceUserFB = proc_addr;

    get_instance_proc_addr(instance, "xrCreateSpatialAnchorAsyncBD", &proc_addr);
    dispatch_table->CreateSpatialAnchorAsyncBD = proc_addr;

    get_instance_proc_addr(instance, "xrCreateSpatialAnchorCompleteBD", &proc_addr);
    dispatch_table->CreateSpatialAnchorCompleteBD = proc_addr;

    get_instance_proc_addr(instance, "xrCreateSpatialAnchorEXT", &proc_addr);
    dispatch_table->CreateSpatialAnchorEXT = proc_addr;

    get_instance_proc_addr(instance, "xrCreateSpatialAnchorFB", &proc_addr);
    dispatch_table->CreateSpatialAnchorFB = proc_addr;

    get_instance_proc_addr(instance, "xrCreateSpatialAnchorFromPerceptionAnchorMSFT", &proc_addr);
    dispatch_table->CreateSpatialAnchorFromPerceptionAnchorMSFT = proc_addr;

    get_instance_proc_addr(instance, "xrCreateSpatialAnchorFromPersistedNameMSFT", &proc_addr);
    dispatch_table->CreateSpatialAnchorFromPersistedNameMSFT = proc_addr;

    get_instance_proc_addr(instance, "xrCreateSpatialAnchorHTC", &proc_addr);
    dispatch_table->CreateSpatialAnchorHTC = proc_addr;

    get_instance_proc_addr(instance, "xrCreateSpatialAnchorMSFT", &proc_addr);
    dispatch_table->CreateSpatialAnchorMSFT = proc_addr;

    get_instance_proc_addr(instance, "xrCreateSpatialAnchorSpaceANDROID", &proc_addr);
    dispatch_table->CreateSpatialAnchorSpaceANDROID = proc_addr;

    get_instance_proc_addr(instance, "xrCreateSpatialAnchorSpaceFromIdANDROID", &proc_addr);
    dispatch_table->CreateSpatialAnchorSpaceFromIdANDROID = proc_addr;

    get_instance_proc_addr(instance, "xrCreateSpatialAnchorSpaceMSFT", &proc_addr);
    dispatch_table->CreateSpatialAnchorSpaceMSFT = proc_addr;

    get_instance_proc_addr(instance, "xrCreateSpatialAnchorStoreConnectionMSFT", &proc_addr);
    dispatch_table->CreateSpatialAnchorStoreConnectionMSFT = proc_addr;

    get_instance_proc_addr(instance, "xrCreateSpatialAnchorsAsyncML", &proc_addr);
    dispatch_table->CreateSpatialAnchorsAsyncML = proc_addr;

    get_instance_proc_addr(instance, "xrCreateSpatialAnchorsCompleteML", &proc_addr);
    dispatch_table->CreateSpatialAnchorsCompleteML = proc_addr;

    get_instance_proc_addr(instance, "xrCreateSpatialAnchorsStorageML", &proc_addr);
    dispatch_table->CreateSpatialAnchorsStorageML = proc_addr;

    get_instance_proc_addr(instance, "xrCreateSpatialAudioRendererBD", &proc_addr);
    dispatch_table->CreateSpatialAudioRendererBD = proc_addr;

    get_instance_proc_addr(instance, "xrCreateSpatialContextAsyncEXT", &proc_addr);
    dispatch_table->CreateSpatialContextAsyncEXT = proc_addr;

    get_instance_proc_addr(instance, "xrCreateSpatialContextCompleteEXT", &proc_addr);
    dispatch_table->CreateSpatialContextCompleteEXT = proc_addr;

    get_instance_proc_addr(instance, "xrCreateSpatialDiscoverySnapshotAsyncEXT", &proc_addr);
    dispatch_table->CreateSpatialDiscoverySnapshotAsyncEXT = proc_addr;

    get_instance_proc_addr(instance, "xrCreateSpatialDiscoverySnapshotCompleteEXT", &proc_addr);
    dispatch_table->CreateSpatialDiscoverySnapshotCompleteEXT = proc_addr;

    get_instance_proc_addr(instance, "xrCreateSpatialEntityAnchorBD", &proc_addr);
    dispatch_table->CreateSpatialEntityAnchorBD = proc_addr;

    get_instance_proc_addr(instance, "xrCreateSpatialEntityFromIdEXT", &proc_addr);
    dispatch_table->CreateSpatialEntityFromIdEXT = proc_addr;

    get_instance_proc_addr(instance, "xrCreateSpatialGraphNodeSpaceMSFT", &proc_addr);
    dispatch_table->CreateSpatialGraphNodeSpaceMSFT = proc_addr;

    get_instance_proc_addr(instance, "xrCreateSpatialPersistenceContextAsyncEXT", &proc_addr);
    dispatch_table->CreateSpatialPersistenceContextAsyncEXT = proc_addr;

    get_instance_proc_addr(instance, "xrCreateSpatialPersistenceContextCompleteEXT", &proc_addr);
    dispatch_table->CreateSpatialPersistenceContextCompleteEXT = proc_addr;

    get_instance_proc_addr(instance, "xrCreateSpatialRaycastSnapshotANDROID", &proc_addr);
    dispatch_table->CreateSpatialRaycastSnapshotANDROID = proc_addr;

    get_instance_proc_addr(instance, "xrCreateSpatialUpdateSnapshotEXT", &proc_addr);
    dispatch_table->CreateSpatialUpdateSnapshotEXT = proc_addr;

    get_instance_proc_addr(instance, "xrCreateSwapchain", &proc_addr);
    dispatch_table->CreateSwapchain = proc_addr;

    get_instance_proc_addr(instance, "xrCreateSwapchainAndroidSurfaceKHR", &proc_addr);
    dispatch_table->CreateSwapchainAndroidSurfaceKHR = proc_addr;

    get_instance_proc_addr(instance, "xrCreateTrackableImageDatabaseAsyncANDROID", &proc_addr);
    dispatch_table->CreateTrackableImageDatabaseAsyncANDROID = proc_addr;

    get_instance_proc_addr(instance, "xrCreateTrackableImageDatabaseCompleteANDROID", &proc_addr);
    dispatch_table->CreateTrackableImageDatabaseCompleteANDROID = proc_addr;

    get_instance_proc_addr(instance, "xrCreateTrackableTrackerANDROID", &proc_addr);
    dispatch_table->CreateTrackableTrackerANDROID = proc_addr;

    get_instance_proc_addr(instance, "xrCreateTriangleMeshFB", &proc_addr);
    dispatch_table->CreateTriangleMeshFB = proc_addr;

    get_instance_proc_addr(instance, "xrCreateVirtualKeyboardMETA", &proc_addr);
    dispatch_table->CreateVirtualKeyboardMETA = proc_addr;

    get_instance_proc_addr(instance, "xrCreateVirtualKeyboardSpaceMETA", &proc_addr);
    dispatch_table->CreateVirtualKeyboardSpaceMETA = proc_addr;

    get_instance_proc_addr(instance, "xrCreateVulkanDeviceKHR", &proc_addr);
    dispatch_table->CreateVulkanDeviceKHR = proc_addr;

    get_instance_proc_addr(instance, "xrCreateVulkanInstanceKHR", &proc_addr);
    dispatch_table->CreateVulkanInstanceKHR = proc_addr;

    get_instance_proc_addr(instance, "xrCreateWorldMeshDetectorML", &proc_addr);
    dispatch_table->CreateWorldMeshDetectorML = proc_addr;

    get_instance_proc_addr(instance, "xrDeleteSpatialAnchorsAsyncML", &proc_addr);
    dispatch_table->DeleteSpatialAnchorsAsyncML = proc_addr;

    get_instance_proc_addr(instance, "xrDeleteSpatialAnchorsCompleteML", &proc_addr);
    dispatch_table->DeleteSpatialAnchorsCompleteML = proc_addr;

    get_instance_proc_addr(instance, "xrDeserializeSceneMSFT", &proc_addr);
    dispatch_table->DeserializeSceneMSFT = proc_addr;

    get_instance_proc_addr(instance, "xrDestroyAction", &proc_addr);
    dispatch_table->DestroyAction = proc_addr;

    get_instance_proc_addr(instance, "xrDestroyActionSet", &proc_addr);
    dispatch_table->DestroyActionSet = proc_addr;

    get_instance_proc_addr(instance, "xrDestroyAnchorBD", &proc_addr);
    dispatch_table->DestroyAnchorBD = proc_addr;

    get_instance_proc_addr(instance, "xrDestroyBodyTrackerBD", &proc_addr);
    dispatch_table->DestroyBodyTrackerBD = proc_addr;

    get_instance_proc_addr(instance, "xrDestroyBodyTrackerFB", &proc_addr);
    dispatch_table->DestroyBodyTrackerFB = proc_addr;

    get_instance_proc_addr(instance, "xrDestroyBodyTrackerHTC", &proc_addr);
    dispatch_table->DestroyBodyTrackerHTC = proc_addr;

    get_instance_proc_addr(instance, "xrDestroyDebugUtilsMessengerEXT", &proc_addr);
    dispatch_table->DestroyDebugUtilsMessengerEXT = proc_addr;

    get_instance_proc_addr(instance, "xrDestroyDeviceAnchorPersistenceANDROID", &proc_addr);
    dispatch_table->DestroyDeviceAnchorPersistenceANDROID = proc_addr;

    get_instance_proc_addr(instance, "xrDestroyEnvironmentDepthProviderMETA", &proc_addr);
    dispatch_table->DestroyEnvironmentDepthProviderMETA = proc_addr;

    get_instance_proc_addr(instance, "xrDestroyEnvironmentDepthSwapchainMETA", &proc_addr);
    dispatch_table->DestroyEnvironmentDepthSwapchainMETA = proc_addr;

    get_instance_proc_addr(instance, "xrDestroyEnvironmentRaycasterMETA", &proc_addr);
    dispatch_table->DestroyEnvironmentRaycasterMETA = proc_addr;

    get_instance_proc_addr(instance, "xrDestroyExportedLocalizationMapML", &proc_addr);
    dispatch_table->DestroyExportedLocalizationMapML = proc_addr;

    get_instance_proc_addr(instance, "xrDestroyEyeTrackerANDROID", &proc_addr);
    dispatch_table->DestroyEyeTrackerANDROID = proc_addr;

    get_instance_proc_addr(instance, "xrDestroyEyeTrackerFB", &proc_addr);
    dispatch_table->DestroyEyeTrackerFB = proc_addr;

    get_instance_proc_addr(instance, "xrDestroyFaceTracker2FB", &proc_addr);
    dispatch_table->DestroyFaceTracker2FB = proc_addr;

    get_instance_proc_addr(instance, "xrDestroyFaceTrackerANDROID", &proc_addr);
    dispatch_table->DestroyFaceTrackerANDROID = proc_addr;

    get_instance_proc_addr(instance, "xrDestroyFaceTrackerBD", &proc_addr);
    dispatch_table->DestroyFaceTrackerBD = proc_addr;

    get_instance_proc_addr(instance, "xrDestroyFaceTrackerFB", &proc_addr);
    dispatch_table->DestroyFaceTrackerFB = proc_addr;

    get_instance_proc_addr(instance, "xrDestroyFacialExpressionClientML", &proc_addr);
    dispatch_table->DestroyFacialExpressionClientML = proc_addr;

    get_instance_proc_addr(instance, "xrDestroyFacialTrackerHTC", &proc_addr);
    dispatch_table->DestroyFacialTrackerHTC = proc_addr;

    get_instance_proc_addr(instance, "xrDestroyFoveationProfileFB", &proc_addr);
    dispatch_table->DestroyFoveationProfileFB = proc_addr;

    get_instance_proc_addr(instance, "xrDestroyGeometryInstanceFB", &proc_addr);
    dispatch_table->DestroyGeometryInstanceFB = proc_addr;

    get_instance_proc_addr(instance, "xrDestroyHandTrackerEXT", &proc_addr);
    dispatch_table->DestroyHandTrackerEXT = proc_addr;

    get_instance_proc_addr(instance, "xrDestroyInstance", &proc_addr);
    dispatch_table->DestroyInstance = proc_addr;

    get_instance_proc_addr(instance, "xrDestroyLightEstimatorANDROID", &proc_addr);
    dispatch_table->DestroyLightEstimatorANDROID = proc_addr;

    get_instance_proc_addr(instance, "xrDestroyMarkerDetectorML", &proc_addr);
    dispatch_table->DestroyMarkerDetectorML = proc_addr;

    get_instance_proc_addr(instance, "xrDestroyPassthroughColorLutMETA", &proc_addr);
    dispatch_table->DestroyPassthroughColorLutMETA = proc_addr;

    get_instance_proc_addr(instance, "xrDestroyPassthroughFB", &proc_addr);
    dispatch_table->DestroyPassthroughFB = proc_addr;

    get_instance_proc_addr(instance, "xrDestroyPassthroughHTC", &proc_addr);
    dispatch_table->DestroyPassthroughHTC = proc_addr;

    get_instance_proc_addr(instance, "xrDestroyPassthroughLayerANDROID", &proc_addr);
    dispatch_table->DestroyPassthroughLayerANDROID = proc_addr;

    get_instance_proc_addr(instance, "xrDestroyPassthroughLayerFB", &proc_addr);
    dispatch_table->DestroyPassthroughLayerFB = proc_addr;

    get_instance_proc_addr(instance, "xrDestroyPlaneDetectorEXT", &proc_addr);
    dispatch_table->DestroyPlaneDetectorEXT = proc_addr;

    get_instance_proc_addr(instance, "xrDestroyRenderModelAssetEXT", &proc_addr);
    dispatch_table->DestroyRenderModelAssetEXT = proc_addr;

    get_instance_proc_addr(instance, "xrDestroyRenderModelEXT", &proc_addr);
    dispatch_table->DestroyRenderModelEXT = proc_addr;

    get_instance_proc_addr(instance, "xrDestroySceneMSFT", &proc_addr);
    dispatch_table->DestroySceneMSFT = proc_addr;

    get_instance_proc_addr(instance, "xrDestroySceneMeshSnapshotANDROID", &proc_addr);
    dispatch_table->DestroySceneMeshSnapshotANDROID = proc_addr;

    get_instance_proc_addr(instance, "xrDestroySceneMeshingTrackerANDROID", &proc_addr);
    dispatch_table->DestroySceneMeshingTrackerANDROID = proc_addr;

    get_instance_proc_addr(instance, "xrDestroySceneObserverMSFT", &proc_addr);
    dispatch_table->DestroySceneObserverMSFT = proc_addr;

    get_instance_proc_addr(instance, "xrDestroySenseDataProviderBD", &proc_addr);
    dispatch_table->DestroySenseDataProviderBD = proc_addr;

    get_instance_proc_addr(instance, "xrDestroySenseDataSnapshotBD", &proc_addr);
    dispatch_table->DestroySenseDataSnapshotBD = proc_addr;

    get_instance_proc_addr(instance, "xrDestroySession", &proc_addr);
    dispatch_table->DestroySession = proc_addr;

    get_instance_proc_addr(instance, "xrDestroySoundFieldBD", &proc_addr);
    dispatch_table->DestroySoundFieldBD = proc_addr;

    get_instance_proc_addr(instance, "xrDestroySoundObjectBD", &proc_addr);
    dispatch_table->DestroySoundObjectBD = proc_addr;

    get_instance_proc_addr(instance, "xrDestroySoundObstacleBD", &proc_addr);
    dispatch_table->DestroySoundObstacleBD = proc_addr;

    get_instance_proc_addr(instance, "xrDestroySoundObstacleMaterialBD", &proc_addr);
    dispatch_table->DestroySoundObstacleMaterialBD = proc_addr;

    get_instance_proc_addr(instance, "xrDestroySpace", &proc_addr);
    dispatch_table->DestroySpace = proc_addr;

    get_instance_proc_addr(instance, "xrDestroySpaceUserFB", &proc_addr);
    dispatch_table->DestroySpaceUserFB = proc_addr;

    get_instance_proc_addr(instance, "xrDestroySpatialAnchorMSFT", &proc_addr);
    dispatch_table->DestroySpatialAnchorMSFT = proc_addr;

    get_instance_proc_addr(instance, "xrDestroySpatialAnchorStoreConnectionMSFT", &proc_addr);
    dispatch_table->DestroySpatialAnchorStoreConnectionMSFT = proc_addr;

    get_instance_proc_addr(instance, "xrDestroySpatialAnchorsStorageML", &proc_addr);
    dispatch_table->DestroySpatialAnchorsStorageML = proc_addr;

    get_instance_proc_addr(instance, "xrDestroySpatialAudioRendererBD", &proc_addr);
    dispatch_table->DestroySpatialAudioRendererBD = proc_addr;

    get_instance_proc_addr(instance, "xrDestroySpatialContextEXT", &proc_addr);
    dispatch_table->DestroySpatialContextEXT = proc_addr;

    get_instance_proc_addr(instance, "xrDestroySpatialEntityEXT", &proc_addr);
    dispatch_table->DestroySpatialEntityEXT = proc_addr;

    get_instance_proc_addr(instance, "xrDestroySpatialGraphNodeBindingMSFT", &proc_addr);
    dispatch_table->DestroySpatialGraphNodeBindingMSFT = proc_addr;

    get_instance_proc_addr(instance, "xrDestroySpatialPersistenceContextEXT", &proc_addr);
    dispatch_table->DestroySpatialPersistenceContextEXT = proc_addr;

    get_instance_proc_addr(instance, "xrDestroySpatialSnapshotEXT", &proc_addr);
    dispatch_table->DestroySpatialSnapshotEXT = proc_addr;

    get_instance_proc_addr(instance, "xrDestroySwapchain", &proc_addr);
    dispatch_table->DestroySwapchain = proc_addr;

    get_instance_proc_addr(instance, "xrDestroyTrackableImageDatabaseANDROID", &proc_addr);
    dispatch_table->DestroyTrackableImageDatabaseANDROID = proc_addr;

    get_instance_proc_addr(instance, "xrDestroyTrackableTrackerANDROID", &proc_addr);
    dispatch_table->DestroyTrackableTrackerANDROID = proc_addr;

    get_instance_proc_addr(instance, "xrDestroyTriangleMeshFB", &proc_addr);
    dispatch_table->DestroyTriangleMeshFB = proc_addr;

    get_instance_proc_addr(instance, "xrDestroyVirtualKeyboardMETA", &proc_addr);
    dispatch_table->DestroyVirtualKeyboardMETA = proc_addr;

    get_instance_proc_addr(instance, "xrDestroyWorldMeshDetectorML", &proc_addr);
    dispatch_table->DestroyWorldMeshDetectorML = proc_addr;

    get_instance_proc_addr(instance, "xrDiscoverSpacesMETA", &proc_addr);
    dispatch_table->DiscoverSpacesMETA = proc_addr;

    get_instance_proc_addr(instance, "xrDownloadSharedSpatialAnchorAsyncBD", &proc_addr);
    dispatch_table->DownloadSharedSpatialAnchorAsyncBD = proc_addr;

    get_instance_proc_addr(instance, "xrDownloadSharedSpatialAnchorCompleteBD", &proc_addr);
    dispatch_table->DownloadSharedSpatialAnchorCompleteBD = proc_addr;

    get_instance_proc_addr(instance, "xrEnableLocalizationEventsML", &proc_addr);
    dispatch_table->EnableLocalizationEventsML = proc_addr;

    get_instance_proc_addr(instance, "xrEnableUserCalibrationEventsML", &proc_addr);
    dispatch_table->EnableUserCalibrationEventsML = proc_addr;

    get_instance_proc_addr(instance, "xrEndAudioPeriodBD", &proc_addr);
    dispatch_table->EndAudioPeriodBD = proc_addr;

    get_instance_proc_addr(instance, "xrEndFrame", &proc_addr);
    dispatch_table->EndFrame = proc_addr;

    get_instance_proc_addr(instance, "xrEndSession", &proc_addr);
    dispatch_table->EndSession = proc_addr;

    get_instance_proc_addr(instance, "xrEnumerateApiLayerProperties", &proc_addr);
    dispatch_table->EnumerateApiLayerProperties = proc_addr;

    get_instance_proc_addr(instance, "xrEnumerateBoundSourcesForAction", &proc_addr);
    dispatch_table->EnumerateBoundSourcesForAction = proc_addr;

    get_instance_proc_addr(instance, "xrEnumerateColorSpacesFB", &proc_addr);
    dispatch_table->EnumerateColorSpacesFB = proc_addr;

    get_instance_proc_addr(instance, "xrEnumerateDisplayRefreshRatesFB", &proc_addr);
    dispatch_table->EnumerateDisplayRefreshRatesFB = proc_addr;

    get_instance_proc_addr(instance, "xrEnumerateEnvironmentBlendModes", &proc_addr);
    dispatch_table->EnumerateEnvironmentBlendModes = proc_addr;

    get_instance_proc_addr(instance, "xrEnumerateEnvironmentDepthSwapchainImagesMETA", &proc_addr);
    dispatch_table->EnumerateEnvironmentDepthSwapchainImagesMETA = proc_addr;

    get_instance_proc_addr(instance, "xrEnumerateExternalCamerasOCULUS", &proc_addr);
    dispatch_table->EnumerateExternalCamerasOCULUS = proc_addr;

    get_instance_proc_addr(instance, "xrEnumerateFacialSimulationModesBD", &proc_addr);
    dispatch_table->EnumerateFacialSimulationModesBD = proc_addr;

    get_instance_proc_addr(instance, "xrEnumerateInstanceExtensionProperties", &proc_addr);
    dispatch_table->EnumerateInstanceExtensionProperties = proc_addr;

    get_instance_proc_addr(instance, "xrEnumerateInteractionRenderModelIdsEXT", &proc_addr);
    dispatch_table->EnumerateInteractionRenderModelIdsEXT = proc_addr;

    get_instance_proc_addr(instance, "xrEnumeratePerformanceMetricsCounterPathsANDROID", &proc_addr);
    dispatch_table->EnumeratePerformanceMetricsCounterPathsANDROID = proc_addr;

    get_instance_proc_addr(instance, "xrEnumeratePerformanceMetricsCounterPathsMETA", &proc_addr);
    dispatch_table->EnumeratePerformanceMetricsCounterPathsMETA = proc_addr;

    get_instance_proc_addr(instance, "xrEnumeratePersistedAnchorsANDROID", &proc_addr);
    dispatch_table->EnumeratePersistedAnchorsANDROID = proc_addr;

    get_instance_proc_addr(instance, "xrEnumeratePersistedSpatialAnchorNamesMSFT", &proc_addr);
    dispatch_table->EnumeratePersistedSpatialAnchorNamesMSFT = proc_addr;

    get_instance_proc_addr(instance, "xrEnumerateRaycastSupportedTrackableTypesANDROID", &proc_addr);
    dispatch_table->EnumerateRaycastSupportedTrackableTypesANDROID = proc_addr;

    get_instance_proc_addr(instance, "xrEnumerateReferenceSpaces", &proc_addr);
    dispatch_table->EnumerateReferenceSpaces = proc_addr;

    get_instance_proc_addr(instance, "xrEnumerateRenderModelPathsFB", &proc_addr);
    dispatch_table->EnumerateRenderModelPathsFB = proc_addr;

    get_instance_proc_addr(instance, "xrEnumerateRenderModelSubactionPathsEXT", &proc_addr);
    dispatch_table->EnumerateRenderModelSubactionPathsEXT = proc_addr;

    get_instance_proc_addr(instance, "xrEnumerateReprojectionModesMSFT", &proc_addr);
    dispatch_table->EnumerateReprojectionModesMSFT = proc_addr;

    get_instance_proc_addr(instance, "xrEnumerateSceneComputeFeaturesMSFT", &proc_addr);
    dispatch_table->EnumerateSceneComputeFeaturesMSFT = proc_addr;

    get_instance_proc_addr(instance, "xrEnumerateSpaceSupportedComponentsFB", &proc_addr);
    dispatch_table->EnumerateSpaceSupportedComponentsFB = proc_addr;

    get_instance_proc_addr(instance, "xrEnumerateSpatialAnchorAttachableComponentsANDROID", &proc_addr);
    dispatch_table->EnumerateSpatialAnchorAttachableComponentsANDROID = proc_addr;

    get_instance_proc_addr(instance, "xrEnumerateSpatialCapabilitiesEXT", &proc_addr);
    dispatch_table->EnumerateSpatialCapabilitiesEXT = proc_addr;

    get_instance_proc_addr(instance, "xrEnumerateSpatialCapabilityComponentTypesEXT", &proc_addr);
    dispatch_table->EnumerateSpatialCapabilityComponentTypesEXT = proc_addr;

    get_instance_proc_addr(instance, "xrEnumerateSpatialCapabilityFeaturesEXT", &proc_addr);
    dispatch_table->EnumerateSpatialCapabilityFeaturesEXT = proc_addr;

    get_instance_proc_addr(instance, "xrEnumerateSpatialEntityComponentTypesBD", &proc_addr);
    dispatch_table->EnumerateSpatialEntityComponentTypesBD = proc_addr;

    get_instance_proc_addr(instance, "xrEnumerateSpatialPersistenceScopesEXT", &proc_addr);
    dispatch_table->EnumerateSpatialPersistenceScopesEXT = proc_addr;

    get_instance_proc_addr(instance, "xrEnumerateSupportedAnchorTrackableTypesANDROID", &proc_addr);
    dispatch_table->EnumerateSupportedAnchorTrackableTypesANDROID = proc_addr;

    get_instance_proc_addr(instance, "xrEnumerateSupportedAudioSampleRateBD", &proc_addr);
    dispatch_table->EnumerateSupportedAudioSampleRateBD = proc_addr;

    get_instance_proc_addr(instance, "xrEnumerateSupportedPersistenceAnchorTypesANDROID", &proc_addr);
    dispatch_table->EnumerateSupportedPersistenceAnchorTypesANDROID = proc_addr;

    get_instance_proc_addr(instance, "xrEnumerateSupportedSemanticLabelSetsANDROID", &proc_addr);
    dispatch_table->EnumerateSupportedSemanticLabelSetsANDROID = proc_addr;

    get_instance_proc_addr(instance, "xrEnumerateSupportedTrackableTypesANDROID", &proc_addr);
    dispatch_table->EnumerateSupportedTrackableTypesANDROID = proc_addr;

    get_instance_proc_addr(instance, "xrEnumerateSwapchainFormats", &proc_addr);
    dispatch_table->EnumerateSwapchainFormats = proc_addr;

    get_instance_proc_addr(instance, "xrEnumerateSwapchainImages", &proc_addr);
    dispatch_table->EnumerateSwapchainImages = proc_addr;

    get_instance_proc_addr(instance, "xrEnumerateViewConfigurationViews", &proc_addr);
    dispatch_table->EnumerateViewConfigurationViews = proc_addr;

    get_instance_proc_addr(instance, "xrEnumerateViewConfigurations", &proc_addr);
    dispatch_table->EnumerateViewConfigurations = proc_addr;

    get_instance_proc_addr(instance, "xrEnumerateViveTrackerPathsHTCX", &proc_addr);
    dispatch_table->EnumerateViveTrackerPathsHTCX = proc_addr;

    get_instance_proc_addr(instance, "xrEraseSpaceFB", &proc_addr);
    dispatch_table->EraseSpaceFB = proc_addr;

    get_instance_proc_addr(instance, "xrEraseSpacesMETA", &proc_addr);
    dispatch_table->EraseSpacesMETA = proc_addr;

    get_instance_proc_addr(instance, "xrFreeWorldMeshBufferML", &proc_addr);
    dispatch_table->FreeWorldMeshBufferML = proc_addr;

    get_instance_proc_addr(instance, "xrGeometryInstanceSetTransformFB", &proc_addr);
    dispatch_table->GeometryInstanceSetTransformFB = proc_addr;

    get_instance_proc_addr(instance, "xrGetActionStateBoolean", &proc_addr);
    dispatch_table->GetActionStateBoolean = proc_addr;

    get_instance_proc_addr(instance, "xrGetActionStateFloat", &proc_addr);
    dispatch_table->GetActionStateFloat = proc_addr;

    get_instance_proc_addr(instance, "xrGetActionStatePose", &proc_addr);
    dispatch_table->GetActionStatePose = proc_addr;

    get_instance_proc_addr(instance, "xrGetActionStateVector2f", &proc_addr);
    dispatch_table->GetActionStateVector2f = proc_addr;

    get_instance_proc_addr(instance, "xrGetAllSubmeshStatesANDROID", &proc_addr);
    dispatch_table->GetAllSubmeshStatesANDROID = proc_addr;

    get_instance_proc_addr(instance, "xrGetAllTrackablesANDROID", &proc_addr);
    dispatch_table->GetAllTrackablesANDROID = proc_addr;

    get_instance_proc_addr(instance, "xrGetAnchorPersistStateANDROID", &proc_addr);
    dispatch_table->GetAnchorPersistStateANDROID = proc_addr;

    get_instance_proc_addr(instance, "xrGetAnchorUuidBD", &proc_addr);
    dispatch_table->GetAnchorUuidBD = proc_addr;

    get_instance_proc_addr(instance, "xrGetAudioInputDeviceGuidOculus", &proc_addr);
    dispatch_table->GetAudioInputDeviceGuidOculus = proc_addr;

    get_instance_proc_addr(instance, "xrGetAudioOutputDeviceGuidOculus", &proc_addr);
    dispatch_table->GetAudioOutputDeviceGuidOculus = proc_addr;

    get_instance_proc_addr(instance, "xrGetBodySkeletonFB", &proc_addr);
    dispatch_table->GetBodySkeletonFB = proc_addr;

    get_instance_proc_addr(instance, "xrGetBodySkeletonHTC", &proc_addr);
    dispatch_table->GetBodySkeletonHTC = proc_addr;

    get_instance_proc_addr(instance, "xrGetCoarseTrackingEyesInfoANDROID", &proc_addr);
    dispatch_table->GetCoarseTrackingEyesInfoANDROID = proc_addr;

    get_instance_proc_addr(instance, "xrGetControllerModelKeyMSFT", &proc_addr);
    dispatch_table->GetControllerModelKeyMSFT = proc_addr;

    get_instance_proc_addr(instance, "xrGetControllerModelPropertiesMSFT", &proc_addr);
    dispatch_table->GetControllerModelPropertiesMSFT = proc_addr;

    get_instance_proc_addr(instance, "xrGetControllerModelStateMSFT", &proc_addr);
    dispatch_table->GetControllerModelStateMSFT = proc_addr;

    get_instance_proc_addr(instance, "xrGetCurrentInteractionProfile", &proc_addr);
    dispatch_table->GetCurrentInteractionProfile = proc_addr;

    get_instance_proc_addr(instance, "xrGetD3D11GraphicsRequirementsKHR", &proc_addr);
    dispatch_table->GetD3D11GraphicsRequirementsKHR = proc_addr;

    get_instance_proc_addr(instance, "xrGetD3D12GraphicsRequirementsKHR", &proc_addr);
    dispatch_table->GetD3D12GraphicsRequirementsKHR = proc_addr;

    get_instance_proc_addr(instance, "xrGetDeviceSampleRateFB", &proc_addr);
    dispatch_table->GetDeviceSampleRateFB = proc_addr;

    get_instance_proc_addr(instance, "xrGetDisplayRefreshRateFB", &proc_addr);
    dispatch_table->GetDisplayRefreshRateFB = proc_addr;

    get_instance_proc_addr(instance, "xrGetEnvironmentDepthSwapchainStateMETA", &proc_addr);
    dispatch_table->GetEnvironmentDepthSwapchainStateMETA = proc_addr;

    get_instance_proc_addr(instance, "xrGetExportedLocalizationMapDataML", &proc_addr);
    dispatch_table->GetExportedLocalizationMapDataML = proc_addr;

    get_instance_proc_addr(instance, "xrGetEyeGazesFB", &proc_addr);
    dispatch_table->GetEyeGazesFB = proc_addr;

    get_instance_proc_addr(instance, "xrGetFaceCalibrationStateANDROID", &proc_addr);
    dispatch_table->GetFaceCalibrationStateANDROID = proc_addr;

    get_instance_proc_addr(instance, "xrGetFaceExpressionWeights2FB", &proc_addr);
    dispatch_table->GetFaceExpressionWeights2FB = proc_addr;

    get_instance_proc_addr(instance, "xrGetFaceExpressionWeightsFB", &proc_addr);
    dispatch_table->GetFaceExpressionWeightsFB = proc_addr;

    get_instance_proc_addr(instance, "xrGetFaceStateANDROID", &proc_addr);
    dispatch_table->GetFaceStateANDROID = proc_addr;

    get_instance_proc_addr(instance, "xrGetFacialExpressionBlendShapePropertiesML", &proc_addr);
    dispatch_table->GetFacialExpressionBlendShapePropertiesML = proc_addr;

    get_instance_proc_addr(instance, "xrGetFacialExpressionsHTC", &proc_addr);
    dispatch_table->GetFacialExpressionsHTC = proc_addr;

    get_instance_proc_addr(instance, "xrGetFacialSimulationDataBD", &proc_addr);
    dispatch_table->GetFacialSimulationDataBD = proc_addr;

    get_instance_proc_addr(instance, "xrGetFacialSimulationModeBD", &proc_addr);
    dispatch_table->GetFacialSimulationModeBD = proc_addr;

    get_instance_proc_addr(instance, "xrGetFineTrackingEyesInfoANDROID", &proc_addr);
    dispatch_table->GetFineTrackingEyesInfoANDROID = proc_addr;

    get_instance_proc_addr(instance, "xrGetFoveationEyeTrackedStateMETA", &proc_addr);
    dispatch_table->GetFoveationEyeTrackedStateMETA = proc_addr;

    get_instance_proc_addr(instance, "xrGetHandGestureQCOM", &proc_addr);
    dispatch_table->GetHandGestureQCOM = proc_addr;

    get_instance_proc_addr(instance, "xrGetHandMeshFB", &proc_addr);
    dispatch_table->GetHandMeshFB = proc_addr;

    get_instance_proc_addr(instance, "xrGetInputSourceLocalizedName", &proc_addr);
    dispatch_table->GetInputSourceLocalizedName = proc_addr;

    get_instance_proc_addr(instance, "xrGetInstanceProcAddr", &proc_addr);
    dispatch_table->GetInstanceProcAddr = proc_addr;

    get_instance_proc_addr(instance, "xrGetInstanceProperties", &proc_addr);
    dispatch_table->GetInstanceProperties = proc_addr;

    get_instance_proc_addr(instance, "xrGetLightEstimateANDROID", &proc_addr);
    dispatch_table->GetLightEstimateANDROID = proc_addr;

    get_instance_proc_addr(instance, "xrGetMarkerDetectorStateML", &proc_addr);
    dispatch_table->GetMarkerDetectorStateML = proc_addr;

    get_instance_proc_addr(instance, "xrGetMarkerLengthML", &proc_addr);
    dispatch_table->GetMarkerLengthML = proc_addr;

    get_instance_proc_addr(instance, "xrGetMarkerNumberML", &proc_addr);
    dispatch_table->GetMarkerNumberML = proc_addr;

    get_instance_proc_addr(instance, "xrGetMarkerReprojectionErrorML", &proc_addr);
    dispatch_table->GetMarkerReprojectionErrorML = proc_addr;

    get_instance_proc_addr(instance, "xrGetMarkerSizeVARJO", &proc_addr);
    dispatch_table->GetMarkerSizeVARJO = proc_addr;

    get_instance_proc_addr(instance, "xrGetMarkerStringML", &proc_addr);
    dispatch_table->GetMarkerStringML = proc_addr;

    get_instance_proc_addr(instance, "xrGetMarkersML", &proc_addr);
    dispatch_table->GetMarkersML = proc_addr;

    get_instance_proc_addr(instance, "xrGetMetalGraphicsRequirementsKHR", &proc_addr);
    dispatch_table->GetMetalGraphicsRequirementsKHR = proc_addr;

    get_instance_proc_addr(instance, "xrGetOpenGLESGraphicsRequirementsKHR", &proc_addr);
    dispatch_table->GetOpenGLESGraphicsRequirementsKHR = proc_addr;

    get_instance_proc_addr(instance, "xrGetOpenGLGraphicsRequirementsKHR", &proc_addr);
    dispatch_table->GetOpenGLGraphicsRequirementsKHR = proc_addr;

    get_instance_proc_addr(instance, "xrGetPassthroughCameraStateANDROID", &proc_addr);
    dispatch_table->GetPassthroughCameraStateANDROID = proc_addr;

    get_instance_proc_addr(instance, "xrGetPassthroughPreferencesMETA", &proc_addr);
    dispatch_table->GetPassthroughPreferencesMETA = proc_addr;

    get_instance_proc_addr(instance, "xrGetPerformanceMetricsStateANDROID", &proc_addr);
    dispatch_table->GetPerformanceMetricsStateANDROID = proc_addr;

    get_instance_proc_addr(instance, "xrGetPerformanceMetricsStateMETA", &proc_addr);
    dispatch_table->GetPerformanceMetricsStateMETA = proc_addr;

    get_instance_proc_addr(instance, "xrGetPlaneDetectionStateEXT", &proc_addr);
    dispatch_table->GetPlaneDetectionStateEXT = proc_addr;

    get_instance_proc_addr(instance, "xrGetPlaneDetectionsEXT", &proc_addr);
    dispatch_table->GetPlaneDetectionsEXT = proc_addr;

    get_instance_proc_addr(instance, "xrGetPlanePolygonBufferEXT", &proc_addr);
    dispatch_table->GetPlanePolygonBufferEXT = proc_addr;

    get_instance_proc_addr(instance, "xrGetQueriedSenseDataBD", &proc_addr);
    dispatch_table->GetQueriedSenseDataBD = proc_addr;

    get_instance_proc_addr(instance, "xrGetRecommendedLayerResolutionMETA", &proc_addr);
    dispatch_table->GetRecommendedLayerResolutionMETA = proc_addr;

    get_instance_proc_addr(instance, "xrGetReferenceSpaceBoundsRect", &proc_addr);
    dispatch_table->GetReferenceSpaceBoundsRect = proc_addr;

    get_instance_proc_addr(instance, "xrGetRenderModelAssetDataEXT", &proc_addr);
    dispatch_table->GetRenderModelAssetDataEXT = proc_addr;

    get_instance_proc_addr(instance, "xrGetRenderModelAssetPropertiesEXT", &proc_addr);
    dispatch_table->GetRenderModelAssetPropertiesEXT = proc_addr;

    get_instance_proc_addr(instance, "xrGetRenderModelPoseTopLevelUserPathEXT", &proc_addr);
    dispatch_table->GetRenderModelPoseTopLevelUserPathEXT = proc_addr;

    get_instance_proc_addr(instance, "xrGetRenderModelPropertiesEXT", &proc_addr);
    dispatch_table->GetRenderModelPropertiesEXT = proc_addr;

    get_instance_proc_addr(instance, "xrGetRenderModelPropertiesFB", &proc_addr);
    dispatch_table->GetRenderModelPropertiesFB = proc_addr;

    get_instance_proc_addr(instance, "xrGetRenderModelStateEXT", &proc_addr);
    dispatch_table->GetRenderModelStateEXT = proc_addr;

    get_instance_proc_addr(instance, "xrGetSceneComponentsMSFT", &proc_addr);
    dispatch_table->GetSceneComponentsMSFT = proc_addr;

    get_instance_proc_addr(instance, "xrGetSceneComputeStateMSFT", &proc_addr);
    dispatch_table->GetSceneComputeStateMSFT = proc_addr;

    get_instance_proc_addr(instance, "xrGetSceneMarkerDecodedStringMSFT", &proc_addr);
    dispatch_table->GetSceneMarkerDecodedStringMSFT = proc_addr;

    get_instance_proc_addr(instance, "xrGetSceneMarkerRawDataMSFT", &proc_addr);
    dispatch_table->GetSceneMarkerRawDataMSFT = proc_addr;

    get_instance_proc_addr(instance, "xrGetSceneMeshBuffersMSFT", &proc_addr);
    dispatch_table->GetSceneMeshBuffersMSFT = proc_addr;

    get_instance_proc_addr(instance, "xrGetSenseDataProviderStateBD", &proc_addr);
    dispatch_table->GetSenseDataProviderStateBD = proc_addr;

    get_instance_proc_addr(instance, "xrGetSerializedSceneFragmentDataMSFT", &proc_addr);
    dispatch_table->GetSerializedSceneFragmentDataMSFT = proc_addr;

    get_instance_proc_addr(instance, "xrGetSpaceBoundary2DFB", &proc_addr);
    dispatch_table->GetSpaceBoundary2DFB = proc_addr;

    get_instance_proc_addr(instance, "xrGetSpaceBoundingBox2DFB", &proc_addr);
    dispatch_table->GetSpaceBoundingBox2DFB = proc_addr;

    get_instance_proc_addr(instance, "xrGetSpaceBoundingBox3DFB", &proc_addr);
    dispatch_table->GetSpaceBoundingBox3DFB = proc_addr;

    get_instance_proc_addr(instance, "xrGetSpaceComponentStatusFB", &proc_addr);
    dispatch_table->GetSpaceComponentStatusFB = proc_addr;

    get_instance_proc_addr(instance, "xrGetSpaceContainerFB", &proc_addr);
    dispatch_table->GetSpaceContainerFB = proc_addr;

    get_instance_proc_addr(instance, "xrGetSpaceRoomLayoutFB", &proc_addr);
    dispatch_table->GetSpaceRoomLayoutFB = proc_addr;

    get_instance_proc_addr(instance, "xrGetSpaceRoomMeshFaceIndicesMETA", &proc_addr);
    dispatch_table->GetSpaceRoomMeshFaceIndicesMETA = proc_addr;

    get_instance_proc_addr(instance, "xrGetSpaceRoomMeshMETA", &proc_addr);
    dispatch_table->GetSpaceRoomMeshMETA = proc_addr;

    get_instance_proc_addr(instance, "xrGetSpaceSemanticLabelsFB", &proc_addr);
    dispatch_table->GetSpaceSemanticLabelsFB = proc_addr;

    get_instance_proc_addr(instance, "xrGetSpaceTriangleMeshMETA", &proc_addr);
    dispatch_table->GetSpaceTriangleMeshMETA = proc_addr;

    get_instance_proc_addr(instance, "xrGetSpaceUserIdFB", &proc_addr);
    dispatch_table->GetSpaceUserIdFB = proc_addr;

    get_instance_proc_addr(instance, "xrGetSpaceUuidFB", &proc_addr);
    dispatch_table->GetSpaceUuidFB = proc_addr;

    get_instance_proc_addr(instance, "xrGetSpatialAnchorNameHTC", &proc_addr);
    dispatch_table->GetSpatialAnchorNameHTC = proc_addr;

    get_instance_proc_addr(instance, "xrGetSpatialAnchorStateML", &proc_addr);
    dispatch_table->GetSpatialAnchorStateML = proc_addr;

    get_instance_proc_addr(instance, "xrGetSpatialBufferFloatEXT", &proc_addr);
    dispatch_table->GetSpatialBufferFloatEXT = proc_addr;

    get_instance_proc_addr(instance, "xrGetSpatialBufferStringEXT", &proc_addr);
    dispatch_table->GetSpatialBufferStringEXT = proc_addr;

    get_instance_proc_addr(instance, "xrGetSpatialBufferUint16EXT", &proc_addr);
    dispatch_table->GetSpatialBufferUint16EXT = proc_addr;

    get_instance_proc_addr(instance, "xrGetSpatialBufferUint32EXT", &proc_addr);
    dispatch_table->GetSpatialBufferUint32EXT = proc_addr;

    get_instance_proc_addr(instance, "xrGetSpatialBufferUint8EXT", &proc_addr);
    dispatch_table->GetSpatialBufferUint8EXT = proc_addr;

    get_instance_proc_addr(instance, "xrGetSpatialBufferVector2fEXT", &proc_addr);
    dispatch_table->GetSpatialBufferVector2fEXT = proc_addr;

    get_instance_proc_addr(instance, "xrGetSpatialBufferVector3fEXT", &proc_addr);
    dispatch_table->GetSpatialBufferVector3fEXT = proc_addr;

    get_instance_proc_addr(instance, "xrGetSpatialEntityComponentDataBD", &proc_addr);
    dispatch_table->GetSpatialEntityComponentDataBD = proc_addr;

    get_instance_proc_addr(instance, "xrGetSpatialEntityUuidBD", &proc_addr);
    dispatch_table->GetSpatialEntityUuidBD = proc_addr;

    get_instance_proc_addr(instance, "xrGetSpatialGraphNodeBindingPropertiesMSFT", &proc_addr);
    dispatch_table->GetSpatialGraphNodeBindingPropertiesMSFT = proc_addr;

    get_instance_proc_addr(instance, "xrGetStationaryReferenceSpaceGenerationIdEXT", &proc_addr);
    dispatch_table->GetStationaryReferenceSpaceGenerationIdEXT = proc_addr;

    get_instance_proc_addr(instance, "xrGetSubmeshDataANDROID", &proc_addr);
    dispatch_table->GetSubmeshDataANDROID = proc_addr;

    get_instance_proc_addr(instance, "xrGetSwapchainStateFB", &proc_addr);
    dispatch_table->GetSwapchainStateFB = proc_addr;

    get_instance_proc_addr(instance, "xrGetSystem", &proc_addr);
    dispatch_table->GetSystem = proc_addr;

    get_instance_proc_addr(instance, "xrGetSystemProperties", &proc_addr);
    dispatch_table->GetSystemProperties = proc_addr;

    get_instance_proc_addr(instance, "xrGetTrackableImageANDROID", &proc_addr);
    dispatch_table->GetTrackableImageANDROID = proc_addr;

    get_instance_proc_addr(instance, "xrGetTrackableMarkerANDROID", &proc_addr);
    dispatch_table->GetTrackableMarkerANDROID = proc_addr;

    get_instance_proc_addr(instance, "xrGetTrackableObjectANDROID", &proc_addr);
    dispatch_table->GetTrackableObjectANDROID = proc_addr;

    get_instance_proc_addr(instance, "xrGetTrackablePlaneANDROID", &proc_addr);
    dispatch_table->GetTrackablePlaneANDROID = proc_addr;

    get_instance_proc_addr(instance, "xrGetTrackableQrCodeANDROID", &proc_addr);
    dispatch_table->GetTrackableQrCodeANDROID = proc_addr;

    get_instance_proc_addr(instance, "xrGetViewConfigurationProperties", &proc_addr);
    dispatch_table->GetViewConfigurationProperties = proc_addr;

    get_instance_proc_addr(instance, "xrGetVirtualKeyboardDirtyTexturesMETA", &proc_addr);
    dispatch_table->GetVirtualKeyboardDirtyTexturesMETA = proc_addr;

    get_instance_proc_addr(instance, "xrGetVirtualKeyboardModelAnimationStatesMETA", &proc_addr);
    dispatch_table->GetVirtualKeyboardModelAnimationStatesMETA = proc_addr;

    get_instance_proc_addr(instance, "xrGetVirtualKeyboardScaleMETA", &proc_addr);
    dispatch_table->GetVirtualKeyboardScaleMETA = proc_addr;

    get_instance_proc_addr(instance, "xrGetVirtualKeyboardTextureDataMETA", &proc_addr);
    dispatch_table->GetVirtualKeyboardTextureDataMETA = proc_addr;

    get_instance_proc_addr(instance, "xrGetVisibilityMaskKHR", &proc_addr);
    dispatch_table->GetVisibilityMaskKHR = proc_addr;

    get_instance_proc_addr(instance, "xrGetVulkanDeviceExtensionsKHR", &proc_addr);
    dispatch_table->GetVulkanDeviceExtensionsKHR = proc_addr;

    get_instance_proc_addr(instance, "xrGetVulkanGraphicsDevice2KHR", &proc_addr);
    dispatch_table->GetVulkanGraphicsDevice2KHR = proc_addr;

    get_instance_proc_addr(instance, "xrGetVulkanGraphicsDeviceKHR", &proc_addr);
    dispatch_table->GetVulkanGraphicsDeviceKHR = proc_addr;

    get_instance_proc_addr(instance, "xrGetVulkanGraphicsRequirementsKHR", &proc_addr);
    dispatch_table->GetVulkanGraphicsRequirementsKHR = proc_addr;

    get_instance_proc_addr(instance, "xrGetVulkanInstanceExtensionsKHR", &proc_addr);
    dispatch_table->GetVulkanInstanceExtensionsKHR = proc_addr;

    get_instance_proc_addr(instance, "xrGetWorldMeshBufferRecommendSizeML", &proc_addr);
    dispatch_table->GetWorldMeshBufferRecommendSizeML = proc_addr;

    get_instance_proc_addr(instance, "xrImportLocalizationMapML", &proc_addr);
    dispatch_table->ImportLocalizationMapML = proc_addr;

    get_instance_proc_addr(instance, "xrInitializeLoaderKHR", &proc_addr);
    dispatch_table->InitializeLoaderKHR = proc_addr;

    get_instance_proc_addr(instance, "xrLoadControllerModelMSFT", &proc_addr);
    dispatch_table->LoadControllerModelMSFT = proc_addr;

    get_instance_proc_addr(instance, "xrLoadRenderModelFB", &proc_addr);
    dispatch_table->LoadRenderModelFB = proc_addr;

    get_instance_proc_addr(instance, "xrLocateBodyJointsBD", &proc_addr);
    dispatch_table->LocateBodyJointsBD = proc_addr;

    get_instance_proc_addr(instance, "xrLocateBodyJointsFB", &proc_addr);
    dispatch_table->LocateBodyJointsFB = proc_addr;

    get_instance_proc_addr(instance, "xrLocateBodyJointsHTC", &proc_addr);
    dispatch_table->LocateBodyJointsHTC = proc_addr;

    get_instance_proc_addr(instance, "xrLocateHandJointsEXT", &proc_addr);
    dispatch_table->LocateHandJointsEXT = proc_addr;

    get_instance_proc_addr(instance, "xrLocateSceneComponentsMSFT", &proc_addr);
    dispatch_table->LocateSceneComponentsMSFT = proc_addr;

    get_instance_proc_addr(instance, "xrLocateSpace", &proc_addr);
    dispatch_table->LocateSpace = proc_addr;

    get_instance_proc_addr(instance, "xrLocateSpaces", &proc_addr);
    dispatch_table->LocateSpaces = proc_addr;

    get_instance_proc_addr(instance, "xrLocateViews", &proc_addr);
    dispatch_table->LocateViews = proc_addr;

    get_instance_proc_addr(instance, "xrNegotiateLoaderApiLayerInterface", &proc_addr);
    dispatch_table->NegotiateLoaderApiLayerInterface = proc_addr;

    get_instance_proc_addr(instance, "xrNegotiateLoaderRuntimeInterface", &proc_addr);
    dispatch_table->NegotiateLoaderRuntimeInterface = proc_addr;

    get_instance_proc_addr(instance, "xrPassthroughLayerPauseFB", &proc_addr);
    dispatch_table->PassthroughLayerPauseFB = proc_addr;

    get_instance_proc_addr(instance, "xrPassthroughLayerResumeFB", &proc_addr);
    dispatch_table->PassthroughLayerResumeFB = proc_addr;

    get_instance_proc_addr(instance, "xrPassthroughLayerSetKeyboardHandsIntensityFB", &proc_addr);
    dispatch_table->PassthroughLayerSetKeyboardHandsIntensityFB = proc_addr;

    get_instance_proc_addr(instance, "xrPassthroughLayerSetStyleFB", &proc_addr);
    dispatch_table->PassthroughLayerSetStyleFB = proc_addr;

    get_instance_proc_addr(instance, "xrPassthroughPauseFB", &proc_addr);
    dispatch_table->PassthroughPauseFB = proc_addr;

    get_instance_proc_addr(instance, "xrPassthroughStartFB", &proc_addr);
    dispatch_table->PassthroughStartFB = proc_addr;

    get_instance_proc_addr(instance, "xrPathToString", &proc_addr);
    dispatch_table->PathToString = proc_addr;

    get_instance_proc_addr(instance, "xrPauseSimultaneousHandsAndControllersTrackingMETA", &proc_addr);
    dispatch_table->PauseSimultaneousHandsAndControllersTrackingMETA = proc_addr;

    get_instance_proc_addr(instance, "xrPerfSettingsSetPerformanceLevelEXT", &proc_addr);
    dispatch_table->PerfSettingsSetPerformanceLevelEXT = proc_addr;

    get_instance_proc_addr(instance, "xrPerformEnvironmentRaycastMETA", &proc_addr);
    dispatch_table->PerformEnvironmentRaycastMETA = proc_addr;

    get_instance_proc_addr(instance, "xrPersistAnchorANDROID", &proc_addr);
    dispatch_table->PersistAnchorANDROID = proc_addr;

    get_instance_proc_addr(instance, "xrPersistSpatialAnchorAsyncBD", &proc_addr);
    dispatch_table->PersistSpatialAnchorAsyncBD = proc_addr;

    get_instance_proc_addr(instance, "xrPersistSpatialAnchorCompleteBD", &proc_addr);
    dispatch_table->PersistSpatialAnchorCompleteBD = proc_addr;

    get_instance_proc_addr(instance, "xrPersistSpatialAnchorMSFT", &proc_addr);
    dispatch_table->PersistSpatialAnchorMSFT = proc_addr;

    get_instance_proc_addr(instance, "xrPersistSpatialEntityAsyncEXT", &proc_addr);
    dispatch_table->PersistSpatialEntityAsyncEXT = proc_addr;

    get_instance_proc_addr(instance, "xrPersistSpatialEntityCompleteEXT", &proc_addr);
    dispatch_table->PersistSpatialEntityCompleteEXT = proc_addr;

    get_instance_proc_addr(instance, "xrPollEvent", &proc_addr);
    dispatch_table->PollEvent = proc_addr;

    get_instance_proc_addr(instance, "xrPollFutureEXT", &proc_addr);
    dispatch_table->PollFutureEXT = proc_addr;

    get_instance_proc_addr(instance, "xrPublishSpatialAnchorsAsyncML", &proc_addr);
    dispatch_table->PublishSpatialAnchorsAsyncML = proc_addr;

    get_instance_proc_addr(instance, "xrPublishSpatialAnchorsCompleteML", &proc_addr);
    dispatch_table->PublishSpatialAnchorsCompleteML = proc_addr;

    get_instance_proc_addr(instance, "xrQueryFramesPerBufferRangeBD", &proc_addr);
    dispatch_table->QueryFramesPerBufferRangeBD = proc_addr;

    get_instance_proc_addr(instance, "xrQueryLocalizationMapsML", &proc_addr);
    dispatch_table->QueryLocalizationMapsML = proc_addr;

    get_instance_proc_addr(instance, "xrQueryPerformanceMetricsCounterANDROID", &proc_addr);
    dispatch_table->QueryPerformanceMetricsCounterANDROID = proc_addr;

    get_instance_proc_addr(instance, "xrQueryPerformanceMetricsCounterMETA", &proc_addr);
    dispatch_table->QueryPerformanceMetricsCounterMETA = proc_addr;

    get_instance_proc_addr(instance, "xrQuerySenseDataAsyncBD", &proc_addr);
    dispatch_table->QuerySenseDataAsyncBD = proc_addr;

    get_instance_proc_addr(instance, "xrQuerySenseDataCompleteBD", &proc_addr);
    dispatch_table->QuerySenseDataCompleteBD = proc_addr;

    get_instance_proc_addr(instance, "xrQuerySpacesFB", &proc_addr);
    dispatch_table->QuerySpacesFB = proc_addr;

    get_instance_proc_addr(instance, "xrQuerySpatialAnchorsAsyncML", &proc_addr);
    dispatch_table->QuerySpatialAnchorsAsyncML = proc_addr;

    get_instance_proc_addr(instance, "xrQuerySpatialAnchorsCompleteML", &proc_addr);
    dispatch_table->QuerySpatialAnchorsCompleteML = proc_addr;

    get_instance_proc_addr(instance, "xrQuerySpatialComponentDataEXT", &proc_addr);
    dispatch_table->QuerySpatialComponentDataEXT = proc_addr;

    get_instance_proc_addr(instance, "xrQuerySystemTrackedKeyboardFB", &proc_addr);
    dispatch_table->QuerySystemTrackedKeyboardFB = proc_addr;

    get_instance_proc_addr(instance, "xrRaycastANDROID", &proc_addr);
    dispatch_table->RaycastANDROID = proc_addr;

    get_instance_proc_addr(instance, "xrReleaseSwapchainImage", &proc_addr);
    dispatch_table->ReleaseSwapchainImage = proc_addr;

    get_instance_proc_addr(instance, "xrRemoveTrackableImageDatabaseANDROID", &proc_addr);
    dispatch_table->RemoveTrackableImageDatabaseANDROID = proc_addr;

    get_instance_proc_addr(instance, "xrRequestBodyTrackingFidelityMETA", &proc_addr);
    dispatch_table->RequestBodyTrackingFidelityMETA = proc_addr;

    get_instance_proc_addr(instance, "xrRequestBoundaryVisibilityMETA", &proc_addr);
    dispatch_table->RequestBoundaryVisibilityMETA = proc_addr;

    get_instance_proc_addr(instance, "xrRequestDisplayRefreshRateFB", &proc_addr);
    dispatch_table->RequestDisplayRefreshRateFB = proc_addr;

    get_instance_proc_addr(instance, "xrRequestExitSession", &proc_addr);
    dispatch_table->RequestExitSession = proc_addr;

    get_instance_proc_addr(instance, "xrRequestMapLocalizationML", &proc_addr);
    dispatch_table->RequestMapLocalizationML = proc_addr;

    get_instance_proc_addr(instance, "xrRequestSceneCaptureFB", &proc_addr);
    dispatch_table->RequestSceneCaptureFB = proc_addr;

    get_instance_proc_addr(instance, "xrRequestWorldMeshAsyncML", &proc_addr);
    dispatch_table->RequestWorldMeshAsyncML = proc_addr;

    get_instance_proc_addr(instance, "xrRequestWorldMeshCompleteML", &proc_addr);
    dispatch_table->RequestWorldMeshCompleteML = proc_addr;

    get_instance_proc_addr(instance, "xrRequestWorldMeshStateAsyncML", &proc_addr);
    dispatch_table->RequestWorldMeshStateAsyncML = proc_addr;

    get_instance_proc_addr(instance, "xrRequestWorldMeshStateCompleteML", &proc_addr);
    dispatch_table->RequestWorldMeshStateCompleteML = proc_addr;

    get_instance_proc_addr(instance, "xrResetBodyTrackingCalibrationMETA", &proc_addr);
    dispatch_table->ResetBodyTrackingCalibrationMETA = proc_addr;

    get_instance_proc_addr(instance, "xrResultToString", &proc_addr);
    dispatch_table->ResultToString = proc_addr;

    get_instance_proc_addr(instance, "xrResumeSimultaneousHandsAndControllersTrackingMETA", &proc_addr);
    dispatch_table->ResumeSimultaneousHandsAndControllersTrackingMETA = proc_addr;

    get_instance_proc_addr(instance, "xrRetrieveSpaceDiscoveryResultsMETA", &proc_addr);
    dispatch_table->RetrieveSpaceDiscoveryResultsMETA = proc_addr;

    get_instance_proc_addr(instance, "xrRetrieveSpaceQueryResultsFB", &proc_addr);
    dispatch_table->RetrieveSpaceQueryResultsFB = proc_addr;

    get_instance_proc_addr(instance, "xrSaveSpaceFB", &proc_addr);
    dispatch_table->SaveSpaceFB = proc_addr;

    get_instance_proc_addr(instance, "xrSaveSpaceListFB", &proc_addr);
    dispatch_table->SaveSpaceListFB = proc_addr;

    get_instance_proc_addr(instance, "xrSaveSpacesMETA", &proc_addr);
    dispatch_table->SaveSpacesMETA = proc_addr;

    get_instance_proc_addr(instance, "xrSendVirtualKeyboardInputMETA", &proc_addr);
    dispatch_table->SendVirtualKeyboardInputMETA = proc_addr;

    get_instance_proc_addr(instance, "xrSessionBeginDebugUtilsLabelRegionEXT", &proc_addr);
    dispatch_table->SessionBeginDebugUtilsLabelRegionEXT = proc_addr;

    get_instance_proc_addr(instance, "xrSessionEndDebugUtilsLabelRegionEXT", &proc_addr);
    dispatch_table->SessionEndDebugUtilsLabelRegionEXT = proc_addr;

    get_instance_proc_addr(instance, "xrSessionInsertDebugUtilsLabelEXT", &proc_addr);
    dispatch_table->SessionInsertDebugUtilsLabelEXT = proc_addr;

    get_instance_proc_addr(instance, "xrSetAndroidApplicationThreadKHR", &proc_addr);
    dispatch_table->SetAndroidApplicationThreadKHR = proc_addr;

    get_instance_proc_addr(instance, "xrSetColorSpaceFB", &proc_addr);
    dispatch_table->SetColorSpaceFB = proc_addr;

    get_instance_proc_addr(instance, "xrSetDebugUtilsObjectNameEXT", &proc_addr);
    dispatch_table->SetDebugUtilsObjectNameEXT = proc_addr;

    get_instance_proc_addr(instance, "xrSetDigitalLensControlALMALENCE", &proc_addr);
    dispatch_table->SetDigitalLensControlALMALENCE = proc_addr;

    get_instance_proc_addr(instance, "xrSetEnvironmentDepthEstimationVARJO", &proc_addr);
    dispatch_table->SetEnvironmentDepthEstimationVARJO = proc_addr;

    get_instance_proc_addr(instance, "xrSetEnvironmentDepthHandRemovalMETA", &proc_addr);
    dispatch_table->SetEnvironmentDepthHandRemovalMETA = proc_addr;

    get_instance_proc_addr(instance, "xrSetFacialSimulationModeBD", &proc_addr);
    dispatch_table->SetFacialSimulationModeBD = proc_addr;

    get_instance_proc_addr(instance, "xrSetInputDeviceActiveEXT", &proc_addr);
    dispatch_table->SetInputDeviceActiveEXT = proc_addr;

    get_instance_proc_addr(instance, "xrSetInputDeviceLocationEXT", &proc_addr);
    dispatch_table->SetInputDeviceLocationEXT = proc_addr;

    get_instance_proc_addr(instance, "xrSetInputDeviceStateBoolEXT", &proc_addr);
    dispatch_table->SetInputDeviceStateBoolEXT = proc_addr;

    get_instance_proc_addr(instance, "xrSetInputDeviceStateFloatEXT", &proc_addr);
    dispatch_table->SetInputDeviceStateFloatEXT = proc_addr;

    get_instance_proc_addr(instance, "xrSetInputDeviceStateVector2fEXT", &proc_addr);
    dispatch_table->SetInputDeviceStateVector2fEXT = proc_addr;

    get_instance_proc_addr(instance, "xrSetMarkerTrackingPredictionVARJO", &proc_addr);
    dispatch_table->SetMarkerTrackingPredictionVARJO = proc_addr;

    get_instance_proc_addr(instance, "xrSetMarkerTrackingTimeoutVARJO", &proc_addr);
    dispatch_table->SetMarkerTrackingTimeoutVARJO = proc_addr;

    get_instance_proc_addr(instance, "xrSetMarkerTrackingVARJO", &proc_addr);
    dispatch_table->SetMarkerTrackingVARJO = proc_addr;

    get_instance_proc_addr(instance, "xrSetPassthroughLayerMeshANDROID", &proc_addr);
    dispatch_table->SetPassthroughLayerMeshANDROID = proc_addr;

    get_instance_proc_addr(instance, "xrSetPerformanceMetricsStateANDROID", &proc_addr);
    dispatch_table->SetPerformanceMetricsStateANDROID = proc_addr;

    get_instance_proc_addr(instance, "xrSetPerformanceMetricsStateMETA", &proc_addr);
    dispatch_table->SetPerformanceMetricsStateMETA = proc_addr;

    get_instance_proc_addr(instance, "xrSetSpaceComponentStatusFB", &proc_addr);
    dispatch_table->SetSpaceComponentStatusFB = proc_addr;

    get_instance_proc_addr(instance, "xrSetSystemNotificationsML", &proc_addr);
    dispatch_table->SetSystemNotificationsML = proc_addr;

    get_instance_proc_addr(instance, "xrSetTilePropertiesHintMETA", &proc_addr);
    dispatch_table->SetTilePropertiesHintMETA = proc_addr;

    get_instance_proc_addr(instance, "xrSetTrackingOptimizationSettingsHintQCOM", &proc_addr);
    dispatch_table->SetTrackingOptimizationSettingsHintQCOM = proc_addr;

    get_instance_proc_addr(instance, "xrSetViewOffsetVARJO", &proc_addr);
    dispatch_table->SetViewOffsetVARJO = proc_addr;

    get_instance_proc_addr(instance, "xrSetVirtualKeyboardModelVisibilityMETA", &proc_addr);
    dispatch_table->SetVirtualKeyboardModelVisibilityMETA = proc_addr;

    get_instance_proc_addr(instance, "xrShareAnchorANDROID", &proc_addr);
    dispatch_table->ShareAnchorANDROID = proc_addr;

    get_instance_proc_addr(instance, "xrShareSpacesFB", &proc_addr);
    dispatch_table->ShareSpacesFB = proc_addr;

    get_instance_proc_addr(instance, "xrShareSpacesMETA", &proc_addr);
    dispatch_table->ShareSpacesMETA = proc_addr;

    get_instance_proc_addr(instance, "xrShareSpatialAnchorAsyncBD", &proc_addr);
    dispatch_table->ShareSpatialAnchorAsyncBD = proc_addr;

    get_instance_proc_addr(instance, "xrShareSpatialAnchorCompleteBD", &proc_addr);
    dispatch_table->ShareSpatialAnchorCompleteBD = proc_addr;

    get_instance_proc_addr(instance, "xrSnapshotMarkerDetectorML", &proc_addr);
    dispatch_table->SnapshotMarkerDetectorML = proc_addr;

    get_instance_proc_addr(instance, "xrStartColocationAdvertisementMETA", &proc_addr);
    dispatch_table->StartColocationAdvertisementMETA = proc_addr;

    get_instance_proc_addr(instance, "xrStartColocationDiscoveryMETA", &proc_addr);
    dispatch_table->StartColocationDiscoveryMETA = proc_addr;

    get_instance_proc_addr(instance, "xrStartEnvironmentDepthProviderMETA", &proc_addr);
    dispatch_table->StartEnvironmentDepthProviderMETA = proc_addr;

    get_instance_proc_addr(instance, "xrStartSenseDataProviderAsyncBD", &proc_addr);
    dispatch_table->StartSenseDataProviderAsyncBD = proc_addr;

    get_instance_proc_addr(instance, "xrStartSenseDataProviderCompleteBD", &proc_addr);
    dispatch_table->StartSenseDataProviderCompleteBD = proc_addr;

    get_instance_proc_addr(instance, "xrStopColocationAdvertisementMETA", &proc_addr);
    dispatch_table->StopColocationAdvertisementMETA = proc_addr;

    get_instance_proc_addr(instance, "xrStopColocationDiscoveryMETA", &proc_addr);
    dispatch_table->StopColocationDiscoveryMETA = proc_addr;

    get_instance_proc_addr(instance, "xrStopEnvironmentDepthProviderMETA", &proc_addr);
    dispatch_table->StopEnvironmentDepthProviderMETA = proc_addr;

    get_instance_proc_addr(instance, "xrStopHapticFeedback", &proc_addr);
    dispatch_table->StopHapticFeedback = proc_addr;

    get_instance_proc_addr(instance, "xrStopSenseDataProviderBD", &proc_addr);
    dispatch_table->StopSenseDataProviderBD = proc_addr;

    get_instance_proc_addr(instance, "xrStringToPath", &proc_addr);
    dispatch_table->StringToPath = proc_addr;

    get_instance_proc_addr(instance, "xrStructureTypeToString", &proc_addr);
    dispatch_table->StructureTypeToString = proc_addr;

    get_instance_proc_addr(instance, "xrStructureTypeToString2KHR", &proc_addr);
    dispatch_table->StructureTypeToString2KHR = proc_addr;

    get_instance_proc_addr(instance, "xrSubmitDebugUtilsMessageEXT", &proc_addr);
    dispatch_table->SubmitDebugUtilsMessageEXT = proc_addr;

    get_instance_proc_addr(instance, "xrSubmitSoundFieldBufferBD", &proc_addr);
    dispatch_table->SubmitSoundFieldBufferBD = proc_addr;

    get_instance_proc_addr(instance, "xrSubmitSoundObjectBufferBD", &proc_addr);
    dispatch_table->SubmitSoundObjectBufferBD = proc_addr;

    get_instance_proc_addr(instance, "xrSuggestBodyTrackingCalibrationOverrideMETA", &proc_addr);
    dispatch_table->SuggestBodyTrackingCalibrationOverrideMETA = proc_addr;

    get_instance_proc_addr(instance, "xrSuggestInteractionProfileBindings", &proc_addr);
    dispatch_table->SuggestInteractionProfileBindings = proc_addr;

    get_instance_proc_addr(instance, "xrSuggestVirtualKeyboardLocationMETA", &proc_addr);
    dispatch_table->SuggestVirtualKeyboardLocationMETA = proc_addr;

    get_instance_proc_addr(instance, "xrSyncActions", &proc_addr);
    dispatch_table->SyncActions = proc_addr;

    get_instance_proc_addr(instance, "xrThermalGetTemperatureTrendEXT", &proc_addr);
    dispatch_table->ThermalGetTemperatureTrendEXT = proc_addr;

    get_instance_proc_addr(instance, "xrTriangleMeshBeginUpdateFB", &proc_addr);
    dispatch_table->TriangleMeshBeginUpdateFB = proc_addr;

    get_instance_proc_addr(instance, "xrTriangleMeshBeginVertexBufferUpdateFB", &proc_addr);
    dispatch_table->TriangleMeshBeginVertexBufferUpdateFB = proc_addr;

    get_instance_proc_addr(instance, "xrTriangleMeshEndUpdateFB", &proc_addr);
    dispatch_table->TriangleMeshEndUpdateFB = proc_addr;

    get_instance_proc_addr(instance, "xrTriangleMeshEndVertexBufferUpdateFB", &proc_addr);
    dispatch_table->TriangleMeshEndVertexBufferUpdateFB = proc_addr;

    get_instance_proc_addr(instance, "xrTriangleMeshGetIndexBufferFB", &proc_addr);
    dispatch_table->TriangleMeshGetIndexBufferFB = proc_addr;

    get_instance_proc_addr(instance, "xrTriangleMeshGetVertexBufferFB", &proc_addr);
    dispatch_table->TriangleMeshGetVertexBufferFB = proc_addr;

    get_instance_proc_addr(instance, "xrTryCreateSpatialGraphStaticNodeBindingMSFT", &proc_addr);
    dispatch_table->TryCreateSpatialGraphStaticNodeBindingMSFT = proc_addr;

    get_instance_proc_addr(instance, "xrTryGetPerceptionAnchorFromSpatialAnchorMSFT", &proc_addr);
    dispatch_table->TryGetPerceptionAnchorFromSpatialAnchorMSFT = proc_addr;

    get_instance_proc_addr(instance, "xrUnpersistAnchorANDROID", &proc_addr);
    dispatch_table->UnpersistAnchorANDROID = proc_addr;

    get_instance_proc_addr(instance, "xrUnpersistSpatialAnchorAsyncBD", &proc_addr);
    dispatch_table->UnpersistSpatialAnchorAsyncBD = proc_addr;

    get_instance_proc_addr(instance, "xrUnpersistSpatialAnchorCompleteBD", &proc_addr);
    dispatch_table->UnpersistSpatialAnchorCompleteBD = proc_addr;

    get_instance_proc_addr(instance, "xrUnpersistSpatialAnchorMSFT", &proc_addr);
    dispatch_table->UnpersistSpatialAnchorMSFT = proc_addr;

    get_instance_proc_addr(instance, "xrUnpersistSpatialEntityAsyncEXT", &proc_addr);
    dispatch_table->UnpersistSpatialEntityAsyncEXT = proc_addr;

    get_instance_proc_addr(instance, "xrUnpersistSpatialEntityCompleteEXT", &proc_addr);
    dispatch_table->UnpersistSpatialEntityCompleteEXT = proc_addr;

    get_instance_proc_addr(instance, "xrUnshareAnchorANDROID", &proc_addr);
    dispatch_table->UnshareAnchorANDROID = proc_addr;

    get_instance_proc_addr(instance, "xrUpdateHandMeshMSFT", &proc_addr);
    dispatch_table->UpdateHandMeshMSFT = proc_addr;

    get_instance_proc_addr(instance, "xrUpdatePassthroughColorLutMETA", &proc_addr);
    dispatch_table->UpdatePassthroughColorLutMETA = proc_addr;

    get_instance_proc_addr(instance, "xrUpdateSoundFieldConfigBD", &proc_addr);
    dispatch_table->UpdateSoundFieldConfigBD = proc_addr;

    get_instance_proc_addr(instance, "xrUpdateSoundObjectConfigBD", &proc_addr);
    dispatch_table->UpdateSoundObjectConfigBD = proc_addr;

    get_instance_proc_addr(instance, "xrUpdateSoundObstacleConfigBD", &proc_addr);
    dispatch_table->UpdateSoundObstacleConfigBD = proc_addr;

    get_instance_proc_addr(instance, "xrUpdateSoundObstacleMaterialConfigBD", &proc_addr);
    dispatch_table->UpdateSoundObstacleMaterialConfigBD = proc_addr;

    get_instance_proc_addr(instance, "xrUpdateSpatialAnchorsExpirationAsyncML", &proc_addr);
    dispatch_table->UpdateSpatialAnchorsExpirationAsyncML = proc_addr;

    get_instance_proc_addr(instance, "xrUpdateSpatialAnchorsExpirationCompleteML", &proc_addr);
    dispatch_table->UpdateSpatialAnchorsExpirationCompleteML = proc_addr;

    get_instance_proc_addr(instance, "xrUpdateSwapchainFB", &proc_addr);
    dispatch_table->UpdateSwapchainFB = proc_addr;

    get_instance_proc_addr(instance, "xrWaitAudioPeriodBD", &proc_addr);
    dispatch_table->WaitAudioPeriodBD = proc_addr;

    get_instance_proc_addr(instance, "xrWaitFrame", &proc_addr);
    dispatch_table->WaitFrame = proc_addr;

    get_instance_proc_addr(instance, "xrWaitSwapchainImage", &proc_addr);
    dispatch_table->WaitSwapchainImage = proc_addr;

}

void MonoEyeCleanUpDispatchTable(XrGeneratedDispatchTable* dispatch_table) {
    if (dispatch_table) {
        delete dispatch_table;
    }
}

} // namespace monoeye
